"""follow

Revision ID: 3557e6269fe5
Revises: 1fc9b2eb8fdc
Create Date: 2023-05-02 03:58:53.243650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3557e6269fe5'
down_revision = '1fc9b2eb8fdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], name=op.f('fk_follows_followed_id_users')),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name=op.f('fk_follows_follower_id_users')),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.drop_table('followers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('follower_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name='fk_followers_follower_id_users'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_followers_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('follows')
    # ### end Alembic commands ###
