"""model updates

Revision ID: 960494c666e0
Revises: 44cf58c62e12
Create Date: 2023-05-05 11:51:03.852284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960494c666e0'
down_revision = '44cf58c62e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_replies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_username', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_replies', schema=None) as batch_op:
        batch_op.drop_column('user_username')

    # ### end Alembic commands ###
